import React, { Fragment } from 'react';
import { useAsync } from 'react-async-hook';
import WaveformData from 'waveform-data';

const fetchPeaks = async (dataUri: string, type: 'dat' | 'json') => {
  const parsePeaksMethod = type === 'dat' ? 'arrayBuffer' : 'json';
  const peaksResponse = await fetch(dataUri);
  const decodedPeaks = await peaksResponse[parsePeaksMethod]();
  return WaveformData.create(decodedPeaks);
};

type RenderProps = {
  data?: WaveformData;
  loading: boolean;
  error?: Error;
};

type Props = {
  location: string;
  type: 'json' | 'dat';
  children: (args: RenderProps) => JSX.Element;
};

/**
 * Fetches and decodes WaveformData files generated by https://github.com/bbc/audiowaveform.
 *
 * @component
 * @example
 * const location = dat/vocals_mono_8bit.dat
 * const type = 'dat'
 * <BBCWaveformData location={location} type={type}>
 *  {({data, loading, error}) => {
 *    return (
 *      <code>
 *        <pre>{JSON.stringify(data.toJSON(), null, 2)}</pre>
 *      </code>
 *    );
 *  }}
 * </BBCWaveformData>
 */
export const BBCWaveformData = ({ location, type, children }: Props) => {
  const asyncPeaks = useAsync(fetchPeaks, [location, type]);

  return (
    <Fragment>
      {asyncPeaks.loading &&
        children({ loading: true, error: undefined, data: undefined })}
      {asyncPeaks.error &&
        children({ loading: false, error: asyncPeaks.error, data: undefined })}
      {asyncPeaks.result &&
        children({
          loading: false,
          error: undefined,
          data: asyncPeaks.result,
        })}
    </Fragment>
  );
};
